name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push PHP Base Image
        uses: docker/build-push-action@v6
        with:
          context: "php/8.4.1/alpine3.21"
          file: "php/8.4.1/alpine3.21/rr.Dockerfile"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/php:8.4.1-rr,${{ vars.DOCKERHUB_USERNAME }}/php:latest

      - name: Build and Push PHP Image
        uses: docker/build-push-action@v6
        with:
          build-args:
            USERNAME=${{ vars.DOCKERHUB_USERNAME }}
          context: "php/8.4.1/alpine3.21"
          file: "php/8.4.1/alpine3.21/rr-ci.Dockerfile"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/php:8.4.1-rr-ci
