name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU (for multi-platform builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host

    - name: Build and Push PHP Base Image
      uses: docker/build-push-action@v6
      with:
        context: php/8.4.1/alpine3.21
        file: {context}/rr.Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/php:8.4.1-rr,${{ vars.DOCKERHUB_USERNAME }}/php:latest

    - name: Build and Push PHP Image
      uses: docker/build-push-action@v6
      with:
        build-contexts: |
          base=docker-image://localhost:5000/${{ vars.DOCKERHUB_USERNAME }}/php:latest
        context: php/8.4.1/alpine3.21
        file: { context }/rr-ci.Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/php:8.4.1-rr-ci
